rsvplist.settings:
  type: config_object
  lable: RSVP List Content Type Settings
  mapping:
    allowed_type:
      type: sequence
      label: Content type the RSVP can display
      sequence:
        type: string
        label: Content type